# -*- coding: utf-8 -*-
"""Filter.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1srboWjabEX6Knk4GxyEaBFF7AgIX7j-E
"""

import pandas as pd

perfumedb = pd.read_csv("perfume_data_combined.csv")

# Splitting the 'for_gender' column properly and handling missing values
perfumedb["for_gender"] = perfumedb["for_gender"].fillna("")  # Handling missing values
perfumedb["for_gender"] = perfumedb["for_gender"].str.split(" n ")
perfumedb["seasons"] = perfumedb["seasons"].fillna("")  # Handling missing values
perfumedb["seasons"] = perfumedb["seasons"].str.split("  ")

def find(column, search):
    array = []
    for i, value in enumerate(column):
        n = 0
        for term in search:
            if term in value:
                n += 1
                if n == len(search):
                    array.append(i)
    return array

search_gender = ["for women"]# Including 'for women' and 'for men' in the search
search_seasons = ["winter"]  # Define the desired seasons
search_sillage = ["strong"]  # Define the desired sillage
search_main = ["woody","",""]# Adding Main Accords
main_accords_list = find(perfumedb["main accords "], search_main)
gender_list = find(perfumedb["for_gender"], search_gender)
sillage_list = find(perfumedb["sillage"], search_sillage)
seasons_list = find(perfumedb["seasons"], search_seasons)
# Filtering based on common elements in all lists
result = list(set(main_accords_list) & set(gender_list) & set(sillage_list) & set(seasons_list))
for index in result:
    print(perfumedb["name"].iloc[index])